repos:
-   repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    # Don't reformat vendored Conan recipes
    - id: black
      language_version: python3.9
      exclude: packages/conan/recipes/
-   repo: local
    hooks:
      - id: pytest
        name: Check pytest unit tests pass
        entry: pipenv run pytest python/aswfdocker
        pass_filenames: false
        language: system
        types: [python]
      - id: mypy
        name: Check mypy static types match
        entry: pipenv run mypy python/aswfdocker
        pass_filenames: false
        language: system
        types: [python]
      - id: pylint
        name: Check linting with pylint
        entry: pipenv run pylint python/aswfdocker
        pass_filenames: false
        language: system
        types: [python]
