trigger:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - README.md


variables:
  - group: dockerhub-release
  - name: DOCKER_CLI_EXPERIMENTAL
    value: enabled
  - name: DOCKER_BUILDKIT
    value: '1'


jobs:
- template: .azure/build-linux-images.yml
  parameters:
    ci_common_version_by_vfx_year:
      '2018': '1'
      '2019': '1'
      '2020': '1'
      '2021': '2'
    groups:
      -
        name: common
        versions: ['1', '2']
        scripts_folder: 'common'
        cache_key_version: "4.11"
        tests:
          - common
      -
        name: base
        versions: ['2018', '2019', '2020', '2021']
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_image_group_common_1
          - build_image_group_common_2
        tests:
          - base
      -
        name: vfx1
        versions: ['2018', '2019', '2020', '2021']
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_image_group_common_1
          - build_image_group_common_2
        tests:
          - openvdb
      -
        name: vfx2
        versions: ['2018', '2019', '2020', '2021']
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_image_group_common_1
          - build_image_group_common_2
      -
        name: usd
        versions: ['2019', '2020', '2021']
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_image_group_common_1
          - build_image_group_common_2
      -
        name: vfxall
        versions: ['2019', '2020', '2021']
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_image_group_common_1
          - build_image_group_common_2
