trigger:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - README.md


variables:
  - name: CI_COMMON_VERSION
    value: "1.0"
  - group: dockerhub-release
  - name: DOCKER_CLI_EXPERIMENTAL
    value: enabled
  - name: DOCKER_BUILDKIT
    value: '1'


jobs:

- template: .azure/build-linux-packages.yml
  parameters:
    groups:
      -
        name: common
        scripts_folder: common
        versions: ['1']
        cache_key_version: "4.11"
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/master-packages')
        dependsOn: []
      -
        name: base
        versions: ['2018', '2019', '2020']
        scripts_folder: '**'
        cache_key_version: "4.11"
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/master-packages')
        dependsOn: []
      -
        name: baseqt
        versions: ['2018', '2019', '2020']
        scripts_folder: '**'
        cache_key_version: "4.11"
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/master-packages-qt')
        dependsOn: []
      -
        name: basepyside
        versions: ['2018', '2019', '2020']
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_common_1
          - build_package_group_baseqt_2018
          - build_package_group_baseqt_2019
          - build_package_group_baseqt_2020
        condition: |
          and(
            in(dependencies.build_package_group_common_1.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_baseqt_2018.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_baseqt_2019.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_baseqt_2020.result, 'Succeeded', 'Skipped'),
            eq(variables['Build.SourceBranch'], 'refs/heads/master-packages-qt')
          )
      -
        name: vfx
        versions: ['2018', '2019', '2020']
        condition:  |
          and(
            in(dependencies.build_package_group_basepyside_2018.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_basepyside_2019.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_basepyside_2020.result, 'Succeeded', 'Skipped'),
            eq(variables['Build.SourceBranch'], 'refs/heads/master-packages')
          )
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_baseqt_2018
          - build_package_group_baseqt_2019
          - build_package_group_baseqt_2020


- template: .azure/build-linux-images.yml
  parameters:
    images:
      -
        name: common
        version: '1'
        scripts_folder: 'common'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_common_1
        condition: in(dependencies.build_package_group_common_1.result, 'Succeeded', 'Skipped')
        tests:
          - common
      -
        name: base
        version: '2018'
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_common_1
        condition: in(dependencies.build_package_group_common_1.result, 'Succeeded', 'Skipped')
        tests:
          - base
      -
        name: base
        version: '2019'
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_common_1
        condition: in(dependencies.build_package_group_common_1.result, 'Succeeded', 'Skipped')
        tests:
          - base
      -
        name: base
        version: '2020'
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_common_1
        condition: in(dependencies.build_package_group_common_1.result, 'Succeeded', 'Skipped')
        tests:
          - base
      -
        name: vfx
        version: '2018'
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_common_1
          - build_package_group_base_2018
          - build_package_group_baseqt_2018
          - build_package_group_vfx_2018
        condition: |
          and(
            in(dependencies.build_package_group_common_1.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_base_2018.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_baseqt_2018.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_vfx_2018.result, 'Succeeded', 'Skipped')
          )
        tests:
          - openvdb
      -
        name: vfx
        version: '2019'
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_common_1
          - build_package_group_base_2019
          - build_package_group_baseqt_2019
          - build_package_group_vfx_2019
        condition: |
          and(
            in(dependencies.build_package_group_common_1.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_base_2019.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_baseqt_2019.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_vfx_2019.result, 'Succeeded', 'Skipped')
          )
        tests:
          - openvdb
      -
        name: vfx
        version: '2020'
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_common_1
          - build_package_group_base_2020
          - build_package_group_baseqt_2020
          - build_package_group_vfx_2020
        condition: |
          and(
            in(dependencies.build_package_group_common_1.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_base_2020.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_baseqt_2020.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_vfx_2020.result, 'Succeeded', 'Skipped')
          )
        tests: []
