trigger:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - README.md


variables:
  - name: CI_COMMON_VERSION
    value: "1.0"
  - group: dockerhub-release
  - name: DOCKER_CLI_EXPERIMENTAL
    value: enabled
  - name: DOCKER_BUILDKIT
    value: '1'


jobs:
- job: test_aswfdocker
  displayName: Test aswfdocker
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'

    - bash: pip3 install pipenv
      displayName: Install pipenv

    - bash: pipenv install --dev
      displayName: Install aswfdocker

    - bash: pipenv run pytest python/aswfdocker --doctest-modules --junitxml=test-pytest-results.xml --cov=. --cov-report=xml --cov-report=html
      displayName: Run pytest

    - bash: pipenv run mypy -p python/aswfdocker --junit-xml=test-mypy-results.xml
      displayName: Run mypy
      
    - bash: pipenv run prospector -F python/aswfdocker --output-format xunit > test-prospector-results.xml
      displayName: Run prospector linter

    - bash: pipenv run black python --check
      displayName: Run black checker
    
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: 'Publish test results for python aswfdocker package'

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'


- template: .azure/build-linux-packages.yml
  parameters:
    groups:
      -
        name: common
        scripts_folder: common
        versions: ['1']
        cache_key_version: "4.11"
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/master-packages')
        dependsOn: []
      -
        name: base
        versions: ['2018', '2019', '2020']
        scripts_folder: '**'
        cache_key_version: "4.11"
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/master-packages')
        dependsOn: []
      -
        name: baseqt
        versions: ['2018', '2019', '2020']
        scripts_folder: '**'
        cache_key_version: "4.11"
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/master-packages-qt')
        dependsOn: []
      -
        name: basepyside
        versions: ['2018', '2019', '2020']
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_common_1
          - build_package_group_baseqt_2018
          - build_package_group_baseqt_2019
          - build_package_group_baseqt_2020
        condition: |
          and(
            in(dependencies.build_package_group_common_1.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_baseqt_2018.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_baseqt_2019.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_baseqt_2020.result, 'Succeeded', 'Skipped'),
            eq(variables['Build.SourceBranch'], 'refs/heads/master-packages-qt')
          )
      -
        name: vfx
        versions: ['2018', '2019', '2020']
        condition:  |
          and(
            in(dependencies.build_package_group_basepyside_2018.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_basepyside_2019.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_basepyside_2020.result, 'Succeeded', 'Skipped'),
            eq(variables['Build.SourceBranch'], 'refs/heads/master-packages')
          )
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_baseqt_2018
          - build_package_group_baseqt_2019
          - build_package_group_baseqt_2020


- template: .azure/build-linux-images.yml
  parameters:
    images:
      -
        name: common
        version: '1'
        scripts_folder: 'common'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_common_1
        condition: in(dependencies.build_package_group_common_1.result, 'Succeeded', 'Skipped')
        tests:
          - common
      -
        name: base
        version: '2018'
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_common_1
          - build_common_1
        condition: in(dependencies.build_package_group_common_1.result, 'Succeeded', 'Skipped')
        tests:
          - base
      -
        name: base
        version: '2019'
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_common_1
          - build_common_1
        condition: in(dependencies.build_package_group_common_1.result, 'Succeeded', 'Skipped')
        tests:
          - base
      -
        name: base
        version: '2020'
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_common_1
          - build_common_1
        condition: in(dependencies.build_package_group_common_1.result, 'Succeeded', 'Skipped')
        tests:
          - base
      -
        name: vfx
        version: '2018'
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_common_1
          - build_package_group_base_2018
          - build_package_group_baseqt_2018
          - build_package_group_vfx_2018
          - build_common_1
        condition: |
          and(
            in(dependencies.build_package_group_common_1.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_base_2018.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_baseqt_2018.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_vfx_2018.result, 'Succeeded', 'Skipped')
          )
        tests:
          - openvdb
      -
        name: vfx
        version: '2019'
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_common_1
          - build_package_group_base_2019
          - build_package_group_baseqt_2019
          - build_package_group_vfx_2019
          - build_common_1
        condition: |
          and(
            in(dependencies.build_package_group_common_1.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_base_2019.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_baseqt_2019.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_vfx_2019.result, 'Succeeded', 'Skipped')
          )
        tests:
          - openvdb
      -
        name: vfx
        version: '2020'
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_package_group_common_1
          - build_package_group_base_2020
          - build_package_group_baseqt_2020
          - build_package_group_vfx_2020
          - build_common_1
        condition: |
          and(
            in(dependencies.build_package_group_common_1.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_base_2020.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_baseqt_2020.result, 'Succeeded', 'Skipped'),
            in(dependencies.build_package_group_vfx_2020.result, 'Succeeded', 'Skipped')
          )
        tests: []
