
jobs:
  - job: build_docker_images
    displayName: Build Docker Images
    condition: not(eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: 'ubuntu-16.04'
    timeoutInMinutes: 180
    steps:
    - script: docker build -t aswfstaging/ci-base:2019 -f ci-base/Dockerfile .
      displayName: Build ci-base
    - script: docker build -t aswfstaging/ci-ocio:2019 -f ci-ocio/Dockerfile .
      displayName: Build ci-ocio
    - script: docker build -t aswfstaging/ci-openvdb:2019 -f ci-openvdb/Dockerfile .
      displayName: Build ci-openvdb
    - script: docker build -t aswfstaging/ci-openexr:2019 -f ci-openexr/Dockerfile .
      displayName: Build ci-openexr

  - job: build_and_push_docker_images
    displayName: Build and Push Docker Images
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    timeoutInMinutes: 180
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: Docker@2
      displayName: Build ci-base
      inputs:
        command: buildAndPush
        repository: aswfstaging/ci-base
        Dockerfile: ci-base/Dockerfile
        buildContext: .
        containerRegistry: dockerHubConnection
        tags: |
          latest
          2019
          2019.0
    - task: Docker@2
      displayName: Build ci-ocio
      inputs:
        command: buildAndPush
        repository: aswfstaging/ci-ocio
        Dockerfile: ci-ocio/Dockerfile
        buildContext: .
        containerRegistry: dockerHubConnection
        tags: |
          latest
          2019
          2019.0
    - task: Docker@2
      displayName: Build ci-openvdb
      inputs:
        command: buildAndPush
        repository: aswfstaging/ci-openvdb
        Dockerfile: ci-openvdb/Dockerfile
        buildContext: .
        containerRegistry: dockerHubConnection
        tags: |
          latest
          2019
          2019.0
    - task: Docker@2
      displayName: Build ci-openexr
      inputs:
        command: buildAndPush
        repository: aswfstaging/ci-openexr
        Dockerfile: ci-openexr/Dockerfile
        buildContext: .
        containerRegistry: dockerHubConnection
        tags: |
          latest
          2019
          2019.0
