#!/usr/bin/env bash

set -ex

if [ ! -f $DOWNLOADS_DIR/llvmorg-${CLANG_VERSION}.tar.gz ]; then
    curl --location https://github.com/llvm/llvm-project/archive/llvmorg-${CLANG_VERSION}.tar.gz -o $DOWNLOADS_DIR/llvmorg-${CLANG_VERSION}.tar.gz
fi

tar xf $DOWNLOADS_DIR/llvmorg-${CLANG_VERSION}.tar.gz
cd llvm-project-llvmorg-${CLANG_VERSION}

mkdir build
cd build
cmake -DLLVM_ENABLE_PROJECTS=clang \
      -DCMAKE_BUILD_TYPE=Release \
      -DLLVM_TARGETS_TO_BUILD=host \
      -DCMAKE_INSTALL_PREFIX=${ASWF_INSTALL_PREFIX} \
      -DCLANG_INCLUDE_DOCS=OFF \
      -DCLANG_INCLUDE_TESTS=OFF \
      -DCLANG_TOOLS_INCLUDE_EXTRA_DOCS=OFF \
      -DCOMPILER_RT_INCLUDE_TESTS=OFF \
      -DLIBCXX_INCLUDE_TESTS=OFF \
      -DLIBCXX_INCLUDE_DOCS=OFF \
      -DLLVM_INCLUDE_TESTS=OFF \
      -DLLVM_INCLUDE_TOOLS=ON \
      -DLLVM_BUILD_TOOLS=ON \
      -DLLVM_TOOL_LLVM_AR_BUILD=OFF \
      -DLLVM_TOOL_LLVM_AS_BUILD=OFF \
      -DLLVM_TOOL_LLVM_AS_FUZZER_BUILD=OFF \
      -DLLVM_TOOL_LLVM_BUGPOINT_BUILD=OFF \
      -DLLVM_TOOL_LLVM_BUGPOINT_PASSES_BUILD=OFF \
      -DLLVM_TOOL_LLVM_BCANALYZER_BUILD=OFF \
      -DLLVM_TOOL_LLVM_COV_BUILD=OFF \
      -DLLVM_TOOL_LLVM_CXXDUMP_BUILD=OFF \
      -DLLVM_TOOL_LLVM_DSYMUTIL_BUILD=OFF \
      -DLLVM_TOOL_LLVM_LLC_BUILD=OFF \
      -DLLVM_TOOL_LLVM_LLI_BUILD=OFF \
      -DLLVM_TOOL_LLVM_DWARFDUMP_BUILD=OFF \
      -DLLVM_TOOL_LLVM_DIS_BUILD=OFF \
      -DLLVM_TOOL_LLVM_EXTRACT_BUILD=OFF \
      -DLLVM_TOOL_LLVM_C_TEST_BUILD=OFF \
      -DLLVM_TOOL_LLVM_DIFF_BUILD=OFF \
      -DLLVM_TOOL_LLVM_GO_BUILD=OFF \
      -DLLVM_TOOL_LLVM_JITLISTENER_BUILD=OFF \
      -DLLVM_TOOL_LLVM_LTO_BUILD=OFF \
      -DLLVM_TOOL_LLVM_MCMARKUP_BUILD=OFF \
      -DLLVM_TOOL_LLVM_MC_BUILD=OFF \
      -DLLVM_TOOL_LLVM_MC_FUZZER_BUILD=OFF \
      -DLLVM_TOOL_LLVM_NM_BUILD=OFF \
      -DLLVM_TOOL_LLVM_OBJDUMP_BUILD=OFF \
      -DLLVM_TOOL_LLVM_BCANALYZER_BUILD=OFF \
      -DLLVM_TOOL_LLVM_PDBDUMP_BUILD=OFF \
      -DLLVM_TOOL_LLVM_PROFDATA_BUILD=OFF \
      -DLLVM_TOOL_LLVM_RTDYLD_BUILD=OFF \
      -DLLVM_TOOL_LLVM_SIZE_BUILD=OFF \
      -DLLVM_TOOL_LLVM_SPLIT_BUILD=OFF \
      -DLLVM_TOOL_LLVM_STRESS_BUILD=OFF \
      -DLLVM_TOOL_LLVM_SYMBOLIZER_BUILD=OFF \
      -DLLVM_TOOL_LLVM_LTO_BUILD=OFF \
      -DLLVM_TOOL_LLVM_OBJ2YAML_BUILD=OFF \
      -DLLVM_TOOL_LLVM_OPT_BUILD=OFF \
      -DLLVM_TOOL_LLVM_SANCOV_BUILD=OFF \
      -DLLVM_TOOL_LLVM_SANSTATS_BUILD=OFF \
      -DLLVM_TOOL_LLVM_VERIFY_USELISTORDER_BUILD=OFF \
      -DLLVM_TOOL_LLVM_XCODE_TOOLCHAIN_BUILD=OFF \
      -DLLVM_TOOL_LLVM_YAML2OBJ_BUILD=OFF \
      -DLLVM_INCLUDE_EXAMPLES=OFF \
      -DLLVM_BUILD_TESTS=OFF \
      -DLLVM_INCLUDE_GO_TESTS=OFF \
      ../llvm
make -j4
make install

cd ../..
rm -rf llvm-project-llvmorg-${CLANG_VERSION}
