# Copyright (c) Contributors to the conan-center-index Project. All rights reserved.
# Copyright (c) Contributors to the aswf-docker Project. All rights reserved.
# SPDX-License-Identifier: MIT
#
# From: https://github.com/conan-io/conan-center-index/blob/75b9e9922496dc0acc2499df76f8f10601042b60/recipes/nanobind/all/conanfile.py

import os

from conan import ConanFile
from conan.tools.build import check_min_cppstd
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import apply_conandata_patches, export_conandata_patches, get, copy, rename, save
from conan.tools.env import VirtualBuildEnv # ASWF: need to use our own Python

required_conan_version = ">=2.0"


class NanobindConan(ConanFile):
    name = "nanobind"
    description = "Tiny and efficient C++/Python bindings"
    license = "BSD-3-Clause"
    url = "https://github.com/conan-io/conan-center-index"
    homepage = "https://github.com/wjakob/nanobind"
    topics = ("python", "bindings", "nanobind", "header-only")
    package_type = "header-library"
    settings = "os", "arch", "compiler", "build_type"

    def export_sources(self): # ASWF: apply our patches
        export_conandata_patches(self)

    def layout(self):
        cmake_layout(self, src_folder="src")

    def package_id(self):
        self.info.clear()

    # ASWF: requirements() and build_requirements() ensure we find our own Python, Conan env provides the real version
    def requirements(self):
        self.requires("tsl-robin-map/[>=1.3.0 <2]")
        self.requires("cpython/[>=3.0.0]")

    def build_requirements(self):
        self.tool_requires("cpython/[>=3.0.0]")

    def validate(self):
        check_min_cppstd(self, 17)

    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)

    def generate(self):
        VirtualBuildEnv(self).generate() # ASWF: clients need to be able to find Python module
        tc = CMakeToolchain(self)
        tc.cache_variables["NB_TEST"] = False
        tc.cache_variables["NB_USE_SUBMODULE_DEPS"] = False
        tc.generate()
        CMakeDeps(self).generate() # ASWF: clients need to be able to find Python module

    def build(self):
        apply_conandata_patches(self) # ASWF: apply our patches
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        # ASWF: license files in package subdirectory
        copy(self, "LICENSE", self.source_folder, os.path.join(self.package_folder, "licenses", self.name))
        cmake = CMake(self)
        cmake.install()
        # ASWF: clients need to be able to find Python module
        # Relocate from nanobind/ to lib/python{X.Y}/site-packages/nanobind/ so
        # installing to /usr/local lands in the default Python search path.
        py_version = str(self.dependencies["cpython"].ref.version)
        major_minor = ".".join(py_version.split(".")[:2])
        site_pkg_dir = os.path.join(self.package_folder, "lib", f"python{major_minor}", "site-packages")
        os.makedirs(site_pkg_dir, exist_ok=True)
        rename(self,
               os.path.join(self.package_folder, "nanobind"),
               os.path.join(site_pkg_dir, "nanobind"))
        # Write a cmake build module that sets PYTHONPATH at cmake-configure time.
        # rawtoaces and similar consumers run "python -m nanobind --cmake_dir" via
        # execute_process to locate nanobind's cmake dir.  That only works if
        # nanobind's site-packages directory is on PYTHONPATH.  Conan's cmake
        # toolchain includes this module automatically, so ENV{PYTHONPATH} is set
        # before any execute_process call, regardless of VirtualBuildEnv/RunEnv.
        cmake_module = os.path.join(site_pkg_dir, "nanobind", "cmake",
                                    "nanobind-conan-pythonpath.cmake")
        save(self, cmake_module, """\
# Auto-generated by the ASWF nanobind Conan recipe.
# Adds nanobind's site-packages directory to PYTHONPATH so that
# "python -m nanobind --cmake_dir" resolves to this Conan package's cmake dir.
get_filename_component(_NB_CMAKE_DIR  "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)
get_filename_component(_NB_PKG_DIR    "${_NB_CMAKE_DIR}"  DIRECTORY)  # .../nanobind/
get_filename_component(_NB_SITE_PKGS  "${_NB_PKG_DIR}"    DIRECTORY)  # .../site-packages/
if(DEFINED ENV{PYTHONPATH})
    set(ENV{PYTHONPATH} "${_NB_SITE_PKGS}:$ENV{PYTHONPATH}")
else()
    set(ENV{PYTHONPATH} "${_NB_SITE_PKGS}")
endif()
unset(_NB_CMAKE_DIR)
unset(_NB_PKG_DIR)
unset(_NB_SITE_PKGS)
""")

    def package_info(self):
        # Don't generate any CMake files and include the upstream ones
        # Only CMake is officially supported by nanobind: 
        # https://nanobind.readthedocs.io/en/latest/building.html#building
        self.cpp_info.set_property("cmake_find_mode", "none")
        # ASWF: clients need to be able to find Python module
        # Use glob since package_id is cleared and we have no dependency info here.
        import glob
        hits = glob.glob(os.path.join(self.package_folder, "lib", "python*", "site-packages", "nanobind"))
        nanobind_dir = os.path.relpath(hits[0], self.package_folder) if hits else "nanobind"
        site_pkg_dir = os.path.dirname(hits[0]) if hits else self.package_folder
        self.cpp_info.builddirs.append(os.path.join(nanobind_dir, "cmake"))
        self.cpp_info.includedirs = [os.path.join(nanobind_dir, "include")]
        # cmake_build_modules: Conan includes this cmake file in the generated
        # toolchain so ENV{PYTHONPATH} is set before any execute_process call.
        self.cpp_info.set_property("cmake_build_modules",
                                   [os.path.join(nanobind_dir, "cmake",
                                                 "nanobind-conan-pythonpath.cmake")])
        # buildenv/runenv: for consumers that use VirtualBuildEnv/VirtualRunEnv,
        # PYTHONPATH points to site-packages so "python -m nanobind" works.
        self.buildenv_info.prepend_path("PYTHONPATH", site_pkg_dir)
        self.runenv_info.prepend_path("PYTHONPATH", site_pkg_dir)
