# syntax=docker/dockerfile:1.3-labs
# Copyright (c) Contributors to the aswf-docker Project. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# !!! This file is automatically generated from a template and the `image.yaml` file in the same folder !!!

ARG ASWF_ORG
ARG ASWF_PKG_ORG
ARG CI_COMMON_VERSION
ARG ASWF_CLANG_MAJOR_VERSION
ARG ASWF_CONAN_CHANNEL

ARG ASWF_VFXPLATFORM_VERSION


ARG ASWF_BOOST_VERSION
ARG ASWF_CMAKE_VERSION
ARG ASWF_CPPUNIT_VERSION
ARG ASWF_GLEW_VERSION
ARG ASWF_GLFW_VERSION
ARG ASWF_GTEST_VERSION
ARG ASWF_LOG4CPLUS_VERSION
ARG ASWF_PYBIND11_VERSION
ARG ASWF_PYTHON_VERSION
ARG ASWF_TBB_VERSION
ARG ASWF_NUMPY_VERSION
ARG ASWF_VFXPLATFORM_VERSION
ARG ASWF_PYTHON_MAJOR_MINOR_VERSION


# Comment out this block to use Conan packages
FROM ${ASWF_PKG_ORG}/ci-package-boost:$ASWF_VFXPLATFORM_VERSION-$ASWF_BOOST_VERSION as ci-package-boost
FROM ${ASWF_PKG_ORG}/ci-package-cmake:$ASWF_VFXPLATFORM_VERSION-$ASWF_CMAKE_VERSION as ci-package-cmake
FROM ${ASWF_PKG_ORG}/ci-package-cppunit:$ASWF_VFXPLATFORM_VERSION-$ASWF_CPPUNIT_VERSION as ci-package-cppunit
FROM ${ASWF_PKG_ORG}/ci-package-glew:$ASWF_VFXPLATFORM_VERSION-$ASWF_GLEW_VERSION as ci-package-glew
FROM ${ASWF_PKG_ORG}/ci-package-glfw:$ASWF_VFXPLATFORM_VERSION-$ASWF_GLFW_VERSION as ci-package-glfw
FROM ${ASWF_PKG_ORG}/ci-package-log4cplus:$ASWF_VFXPLATFORM_VERSION-$ASWF_LOG4CPLUS_VERSION as ci-package-log4cplus
FROM ${ASWF_PKG_ORG}/ci-package-pybind11:$ASWF_VFXPLATFORM_VERSION-$ASWF_PYBIND11_VERSION as ci-package-pybind11
FROM ${ASWF_PKG_ORG}/ci-package-python:$ASWF_VFXPLATFORM_VERSION-$ASWF_PYTHON_VERSION as ci-package-python
FROM ${ASWF_PKG_ORG}/ci-package-tbb:$ASWF_VFXPLATFORM_VERSION-$ASWF_TBB_VERSION as ci-package-tbb
FROM ${ASWF_ORG}/ci-common:${CI_COMMON_VERSION}-clang${ASWF_CLANG_MAJOR_VERSION} as ci-base


ARG ASWF_ORG
ARG ASWF_PKG_ORG
ARG ASWF_VERSION
ARG CI_COMMON_VERSION
ARG ASWF_CONAN_CHANNEL

ARG ASWF_BOOST_VERSION
ARG ASWF_CMAKE_VERSION
ARG ASWF_CPPUNIT_VERSION
ARG ASWF_GLEW_VERSION
ARG ASWF_GLFW_VERSION
ARG ASWF_GTEST_VERSION
ARG ASWF_LOG4CPLUS_VERSION
ARG ASWF_PYBIND11_VERSION
ARG ASWF_PYTHON_VERSION
ARG ASWF_TBB_VERSION
ARG ASWF_NUMPY_VERSION
ARG ASWF_VFXPLATFORM_VERSION
ARG ASWF_PYTHON_MAJOR_MINOR_VERSION


LABEL org.opencontainers.image.name="$ASWF_ORG/ci-base"
LABEL org.opencontainers.image.title="Base CI Docker Image"
LABEL org.opencontainers.image.description="Contains: Python, TBB, Boost and other base libraries"
LABEL org.opencontainers.image.url="http://aswf.io/"
LABEL org.opencontainers.image.source="https://github.com/AcademySoftwareFoundation/aswf-docker/blob/master/ci-base/Dockerfile"
LABEL org.opencontainers.image.vendor="AcademySoftwareFoundation"
LABEL org.opencontainers.image.authors="Built by aswf.io CI Working Group"
LABEL org.opencontainers.image.version="${ASWF_VERSION}"


LABEL com.vfxplatform.version="${ASWF_VFXPLATFORM_VERSION}"


LABEL io.aswf.docker.versions.boost="$ASWF_BOOST_VERSION"
LABEL io.aswf.docker.versions.cmake="$ASWF_CMAKE_VERSION"
LABEL io.aswf.docker.versions.cppunit="$ASWF_CPPUNIT_VERSION"
LABEL io.aswf.docker.versions.glew="$ASWF_GLEW_VERSION"
LABEL io.aswf.docker.versions.glfw="$ASWF_GLFW_VERSION"
LABEL io.aswf.docker.versions.gtest="$ASWF_GTEST_VERSION"
LABEL io.aswf.docker.versions.log4cplus="$ASWF_LOG4CPLUS_VERSION"
LABEL io.aswf.docker.versions.pybind11="$ASWF_PYBIND11_VERSION"
LABEL io.aswf.docker.versions.python="$ASWF_PYTHON_VERSION"
LABEL io.aswf.docker.versions.tbb="$ASWF_TBB_VERSION"
LABEL io.aswf.docker.versions.numpy="$ASWF_NUMPY_VERSION"
LABEL io.aswf.docker.versions.vfxplatform="$ASWF_VFXPLATFORM_VERSION"


ENV ASWF_ORG=${ASWF_ORG}
ENV ASWF_VERSION=${ASWF_VERSION}

ENV ASWF_VFXPLATFORM_VERSION=${ASWF_VFXPLATFORM_VERSION}


ENV ASWF_BOOST_VERSION=$ASWF_BOOST_VERSION
ENV ASWF_CMAKE_VERSION=$ASWF_CMAKE_VERSION
ENV ASWF_CPPUNIT_VERSION=$ASWF_CPPUNIT_VERSION
ENV ASWF_GLEW_VERSION=$ASWF_GLEW_VERSION
ENV ASWF_GLFW_VERSION=$ASWF_GLFW_VERSION
ENV ASWF_GTEST_VERSION=$ASWF_GTEST_VERSION
ENV ASWF_LOG4CPLUS_VERSION=$ASWF_LOG4CPLUS_VERSION
ENV ASWF_PYBIND11_VERSION=$ASWF_PYBIND11_VERSION
ENV ASWF_PYTHON_VERSION=$ASWF_PYTHON_VERSION
ENV ASWF_TBB_VERSION=$ASWF_TBB_VERSION
ENV ASWF_NUMPY_VERSION=$ASWF_NUMPY_VERSION
ENV ASWF_VFXPLATFORM_VERSION=$ASWF_VFXPLATFORM_VERSION
ENV ASWF_PYTHON_MAJOR_MINOR_VERSION=$ASWF_PYTHON_MAJOR_MINOR_VERSION


# Comment out this block to use Conan packages
COPY --from=ci-package-boost /. /usr/local/
COPY --from=ci-package-cmake /. /usr/local/
COPY --from=ci-package-cppunit /. /usr/local/
COPY --from=ci-package-glew /. /usr/local/
COPY --from=ci-package-glfw /. /usr/local/
COPY --from=ci-package-log4cplus /. /usr/local/
COPY --from=ci-package-pybind11 /. /usr/local/
COPY --from=ci-package-python /. /usr/local/
COPY --from=ci-package-tbb /. /usr/local/
COPY ci-base/README.md ci-base/image.yaml /usr/local/aswf/



ENV PYTHONPATH=/usr/local/lib/python${ASWF_PYTHON_MAJOR_MINOR_VERSION}/site-packages:/usr/local/lib64/python${ASWF_PYTHON_MAJOR_MINOR_VERSION}/site-packages:/usr/local/lib/python:${PYTHONPATH}

RUN conan config set general.default_profile=vfx${ASWF_VFXPLATFORM_VERSION}



# conan-only packages
COPY <<EOF /usr/local/conanfile.txt
[generators]
[imports]
., * -> .
[requires]
# Uncomment to use Conan packages instead of Docker ones
# boost/${ASWF_BOOST_VERSION}@${ASWF_PKG_ORG}/${ASWF_CONAN_CHANNEL}
# cmake/${ASWF_CMAKE_VERSION}@${ASWF_PKG_ORG}/${ASWF_CONAN_CHANNEL}
# cppunit/${ASWF_CPPUNIT_VERSION}@${ASWF_PKG_ORG}/${ASWF_CONAN_CHANNEL}
# glew/${ASWF_GLEW_VERSION}@${ASWF_PKG_ORG}/${ASWF_CONAN_CHANNEL}
# glfw/${ASWF_GLFW_VERSION}@${ASWF_PKG_ORG}/${ASWF_CONAN_CHANNEL}
gtest/${ASWF_GTEST_VERSION}@${ASWF_PKG_ORG}/${ASWF_CONAN_CHANNEL}
# log4cplus/${ASWF_LOG4CPLUS_VERSION}@${ASWF_PKG_ORG}/${ASWF_CONAN_CHANNEL}
# pybind11/${ASWF_PYBIND11_VERSION}@${ASWF_PKG_ORG}/${ASWF_CONAN_CHANNEL}
# python/${ASWF_PYTHON_VERSION}@${ASWF_PKG_ORG}/${ASWF_CONAN_CHANNEL}
# tbb/${ASWF_TBB_VERSION}@${ASWF_PKG_ORG}/${ASWF_CONAN_CHANNEL}
EOF

RUN <<EOF
cd /usr/local/
conan install .
EOF