trigger:
  tags:
    include:
    - aswf/ci*
    - aswftesting/ci*

variables:
  - group: dockerhub-release

jobs:
  - job: release_image
    displayName: Build and Release ci image
    timeoutInMinutes: 0
    variables:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: '1'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: prepare-docker.yml
        parameters:
          image_name: 'image_tagged_release'
          cache_key_version: "4.11"
          cache_key_folder: "**"

      - bash: |
          set -ex
          aswfdocker \
            --repo-uri $(Build.Repository.Uri) \
            --verbose \
            build \
            --full-name $(Build.SourceBranch) \
            --push YES
        displayName: Build and Push Docker Images
