trigger:
  tags:
    include:
    - aswf/ci*
    - aswftesting/ci*

variables:
  - name: CI_COMMON_VERSION
    value: "1.0"
  - group: dockerhub-release
  - name: DOCKER_CLI_EXPERIMENTAL
    value: enabled
  - name: DOCKER_BUILDKIT
    value: '1'


jobs:
  - job: build_image
    displayName: Build ci image
    timeoutInMinutes: 0
    variables:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: '1'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: prepare-docker.yml
        parameters:
          image_name: 'image_tagged_release'
          cache_key_version: "4.11"
          cache_key_folder: "**"

      - bash: |
          set -ex
          aswfdocker \
            --repo-uri $(Build.Repository.Uri) \
            --verbose \
            build \
            --image-name $(Build.SourceBranch) \
            --push true
        displayName: Build and Push Docker Images
