trigger:
  tags:
    include:
    - aswf/ci*
    - aswftesting/ci*

variables:
  - name: CI_COMMON_VERSION
    value: "1.0"
  - group: dockerhub-release
  - name: DOCKER_CLI_EXPERIMENTAL
    value: enabled
  - name: DOCKER_BUILDKIT
    value: '1'


jobs:

- template: .azure/build-linux-images.yml
  parameters:
    groups:
      -
        name: common
        versions: ['1']
        scripts_folder: 'common'
        cache_key_version: "4.11"
        tests:
          - common
      -
        name: base
        versions: ['2018', '2019', '2020']
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_image_group_common_1
        tests:
          - base
      -
        name: openexr
        versions: ['2018', '2019', '2020']
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_image_group_common_1
      -
        name: openvdb
        versions: ['2018', '2019', '2020']
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_image_group_common_1
        tests:
          - openvdb
      -
        name: osl
        versions: ['2018', '2019', '2020']
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_image_group_common_1
      -
        name: opencue
        versions: ['2018', '2019', '2020']
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_image_group_common_1
      -
        name: ocio
        versions: ['2018', '2019', '2020']
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_image_group_common_1
      -
        name: usd
        versions: ['2018', '2019', '2020']
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_image_group_common_1
      -
        name: vfxall
        versions: ['2018', '2019', '2020']
        scripts_folder: '**'
        cache_key_version: "4.11"
        dependsOn: 
          - build_image_group_common_1
