parameters:
  vfxplatform_version: '2019'
  aswf_version: '2019.0'
  python_version: '2.7'
  cicommon_version: '1.0'
  images: []

jobs:
- ${{ each img in parameters.images }}:
  - job: build_${{ img }}_${{ parameters.vfxplatform_version }}
    displayName: Build ci-${{ img }}:${{ parameters.vfxplatform_version }}
    timeoutInMinutes: 0
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: docker login -u $(dockerhub.username) -p $(dockerhub.password)
        displayName: Docker login

      - bash: docker build -t $(dockerhub.org)/ci-${{ img }}:${{ parameters.vfxplatform_version }} -f ci-${{ img }}/Dockerfile \
              --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
              --build-arg VCS_REF=`git rev-parse — short HEAD`
              --build-arg ASWF_ORG=$( dockerhub.org ) \
              --build-arg VFXPLATFORM_VERSION=${{ parameters.vfxplatform_version }} \
              --build-arg CI_COMMON_VERSION=${{ parameters.cicommon_version }} \
              --build-arg PYTHON_VERSION=${{ parameters.python_version }} \
              .
        displayName: Build Docker Images

      - bash: docker push $(dockerhub.org)/ci-${{ img }}:${{ parameters.aswf_version }}
        displayName: Push Docker Images
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
