parameters:
  vfxplatform_version: '2019'
  aswf_version: '2019'

jobs:
- job: build_${{ parameters.vfxplatform_version }}
  displayName: Build ${{ parameters.vfxplatform_version }}
  timeoutInMinutes: 360
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - script: docker login -u $(dockerhub.username) -p $(dockerhub.password)
      displayName: Docker login
    - bash: BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') ./build.sh
      displayName: Build Docker Images
      env:
        VFXPLATFORM_VERSION: ${{ parameters.vfxplatform_version }}
        ASWF_VERSION: ${{ parameters.aswf_version }}
    - bash: |
        docker push $(dockerhub.org)/ci-base:${{ parameters.aswf_version }}
        docker push $(dockerhub.org)/ci-ocio:${{ parameters.aswf_version }}
        docker push $(dockerhub.org)/ci-openvdb:${{ parameters.aswf_version }}
      displayName: Push Docker Images
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
