parameters:
  groups: []

jobs:
- ${{ each group in parameters.groups }}:
  - ${{ each group_version in group.versions }}:
    - job: build_package_group_${{ group.name }}_${{ group_version }}
      displayName: Build package group ${{ group.name }}:${{ group_version }}
      condition: ${{ group.condition }}
      dependsOn: ${{ group.dependsOn }}
      timeoutInMinutes: 0
      variables:
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKER_BUILDKIT: '1'
      pool:
        vmImage: 'ubuntu-18.04'
      steps:
        - template: prepare-docker.yml
          parameters:
            image_name: 'package_${{ group.name }}'
            cache_key_version: ${{ group.cache_key_version }}
            cache_key_folder: ${{ group_version }}

        - bash: |
            set -ex
            aswfdocker \
              --repo-uri $(Build.Repository.Uri) \
              --source-branch $(Build.SourceBranch) \
              --verbose \
              build \
              --ci-image-type PACKAGE \
              --group-name ${{ group.name }} \
              --group-version ${{ group_version }} \
              --push AUTO
          displayName: Create ${{ group.name }}:${{ group_version }} packages

        - bash:  |
            set -ex
            docker run --rm \
              --volumes-from buildx_buildkit_cacheable0 \
              -v $(Pipeline.Workspace)/cache/ci-package_${{ group.name }}:/backup \
              alpine /bin/sh -c "cd / && tar cf /backup/backup.tar.gz /var/lib/buildkit"
          displayName: Save Docker Cache
          condition: eq(variables.DOCKER_CACHE_RESTORED, 'false')
