# syntax=docker/dockerfile:1.3-labs
# Copyright (c) Contributors to the aswf-docker Project. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# !!! This file is automatically generated from a template and the `image.yaml` file in the same folder !!!

ARG ASWF_ORG
ARG ASWF_PKG_ORG
ARG CI_COMMON_VERSION
ARG ASWF_CLANG_MAJOR_VERSION
ARG ASWF_CONAN_CHANNEL

ARG ASWF_VFXPLATFORM_VERSION


ARG ASWF_PYTHON_VERSION
ARG ASWF_CMAKE_VERSION
ARG ASWF_QT_VERSION
ARG ASWF_PYSIDE_VERSION
ARG ASWF_NUMPY_VERSION
ARG ASWF_VFXPLATFORM_VERSION
ARG ASWF_PYTHON_MAJOR_MINOR_VERSION


# Comment out this block to use Conan packages
FROM ${ASWF_PKG_ORG}/ci-package-python:$ASWF_VFXPLATFORM_VERSION-$ASWF_PYTHON_VERSION as ci-package-python
FROM ${ASWF_PKG_ORG}/ci-package-cmake:$ASWF_VFXPLATFORM_VERSION-$ASWF_CMAKE_VERSION as ci-package-cmake
FROM ${ASWF_PKG_ORG}/ci-package-qt:$ASWF_VFXPLATFORM_VERSION-$ASWF_QT_VERSION as ci-package-qt
FROM ${ASWF_PKG_ORG}/ci-package-pyside:$ASWF_VFXPLATFORM_VERSION-$ASWF_PYSIDE_VERSION as ci-package-pyside
FROM ${ASWF_ORG}/ci-common:${CI_COMMON_VERSION}-clang${ASWF_CLANG_MAJOR_VERSION} as ci-otio


ARG ASWF_ORG
ARG ASWF_PKG_ORG
ARG ASWF_VERSION
ARG CI_COMMON_VERSION
ARG ASWF_CONAN_CHANNEL

ARG ASWF_PYTHON_VERSION
ARG ASWF_CMAKE_VERSION
ARG ASWF_QT_VERSION
ARG ASWF_PYSIDE_VERSION
ARG ASWF_NUMPY_VERSION
ARG ASWF_VFXPLATFORM_VERSION
ARG ASWF_PYTHON_MAJOR_MINOR_VERSION


LABEL org.opencontainers.image.name="$ASWF_ORG/ci-otio"
LABEL org.opencontainers.image.title="OpenTimelineIO CI Docker Image"
LABEL org.opencontainers.image.description="Contains: Python, Qt, PySide and other OpenTimelineIO upstream dependencies\
Warning: this image does *not* contain OpenTimelineIO itself as it is used to *build* OpenTimelineIO!"
LABEL org.opencontainers.image.url="http://aswf.io/"
LABEL org.opencontainers.image.source="https://github.com/AcademySoftwareFoundation/aswf-docker/blob/master/ci-otio/Dockerfile"
LABEL org.opencontainers.image.vendor="AcademySoftwareFoundation"
LABEL org.opencontainers.image.authors="Built by aswf.io CI Working Group"
LABEL org.opencontainers.image.version="${ASWF_VERSION}"


LABEL com.vfxplatform.version="${ASWF_VFXPLATFORM_VERSION}"


LABEL io.aswf.docker.versions.python="$ASWF_PYTHON_VERSION"
LABEL io.aswf.docker.versions.cmake="$ASWF_CMAKE_VERSION"
LABEL io.aswf.docker.versions.qt="$ASWF_QT_VERSION"
LABEL io.aswf.docker.versions.pyside="$ASWF_PYSIDE_VERSION"
LABEL io.aswf.docker.versions.numpy="$ASWF_NUMPY_VERSION"
LABEL io.aswf.docker.versions.vfxplatform="$ASWF_VFXPLATFORM_VERSION"


ENV ASWF_ORG=${ASWF_ORG}
ENV ASWF_VERSION=${ASWF_VERSION}

ENV ASWF_VFXPLATFORM_VERSION=${ASWF_VFXPLATFORM_VERSION}


ENV ASWF_PYTHON_VERSION=$ASWF_PYTHON_VERSION
ENV ASWF_CMAKE_VERSION=$ASWF_CMAKE_VERSION
ENV ASWF_QT_VERSION=$ASWF_QT_VERSION
ENV ASWF_PYSIDE_VERSION=$ASWF_PYSIDE_VERSION
ENV ASWF_NUMPY_VERSION=$ASWF_NUMPY_VERSION
ENV ASWF_VFXPLATFORM_VERSION=$ASWF_VFXPLATFORM_VERSION
ENV ASWF_PYTHON_MAJOR_MINOR_VERSION=$ASWF_PYTHON_MAJOR_MINOR_VERSION


# Comment out this block to use Conan packages
COPY --from=ci-package-python /. /usr/local/
COPY --from=ci-package-cmake /. /usr/local/
COPY --from=ci-package-qt /. /usr/local/
COPY --from=ci-package-pyside /. /usr/local/
COPY ci-otio/README.md ci-otio/image.yaml /usr/local/aswf/

RUN sudo pip install flake8 tox urllib3


ENV PYTHONPATH=/usr/local/lib/python${ASWF_PYTHON_MAJOR_MINOR_VERSION}/site-packages:/usr/local/lib64/python${ASWF_PYTHON_MAJOR_MINOR_VERSION}/site-packages:/usr/local/lib/python:${PYTHONPATH}

RUN conan config set general.default_profile=vfx${ASWF_VFXPLATFORM_VERSION}



# conan-only packages
COPY <<EOF /usr/local/conanfile.txt
[generators]
[imports]
., * -> .
[requires]
# Uncomment to use Conan packages instead of Docker ones
# python/${ASWF_PYTHON_VERSION}@${ASWF_PKG_ORG}/${ASWF_CONAN_CHANNEL}
# cmake/${ASWF_CMAKE_VERSION}@${ASWF_PKG_ORG}/${ASWF_CONAN_CHANNEL}
# qt/${ASWF_QT_VERSION}@${ASWF_PKG_ORG}/${ASWF_CONAN_CHANNEL}
# pyside/${ASWF_PYSIDE_VERSION}@${ASWF_PKG_ORG}/${ASWF_CONAN_CHANNEL}
EOF

RUN <<EOF
cd /usr/local/
conan install .
EOF