name: Test Python aswfdocker Library - Sonar

on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip3 install pipenv
      name: Install pipenv

    - run: pipenv install --dev
      name: Install aswfdocker and dev dependencies with pipenv

    # python unittests with junit XML report and coverage XML Cobertura report for publishing task
    - run: pipenv run pytest python/aswfdocker --doctest-modules --junitxml=test-pytest-results.xml --cov=. --cov-report=xml
      name: Run pytest

    # mypy static type checks with junit XML report
    - run: pipenv run mypy python/aswfdocker --junit-xml=test-mypy-results.xml
      name: Run mypy

    # prospector linter checks with xunit XML report
    - run: pipenv run prospector -F python/aswfdocker --output-format xunit > test-prospector-results.xml
      name: Run prospector linter

    - run: git fetch --unshallow
      name: Fetch unshallow to help sonar

    - run: |
        export SONAR_SCANNER_VERSION=4.2.0.1873
        export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
        curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
        unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
        export PATH=$SONAR_SCANNER_HOME/bin:$PATH
        export SONAR_SCANNER_OPTS="-server"
        sonar-scanner \
          -Dsonar.organization=academysoftwarefoundation \
          -Dsonar.projectKey=AcademySoftwareFoundation_aswf_docker \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.projectDate=`git log $tag -n 1 --date=short --pretty="%ad"` \
          -Dsonar.projectVersion=`pipenv run python setup.py --version`
      name: Install and Run Sonar Scanner
