name: Test Python aswfdocker Library - Sonar

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: 3.9
        cache: 'pipenv'
    - name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
    - name: Install aswfdocker and dev dependencies with pipenv
      run: pipenv install --dev

    # mypy static type checks with junit XML report
    - name: Run mypy
      run: pipenv run mypy python/aswfdocker --junit-xml=test-mypy-results.xml

    # python unittests with junit XML report, PyLint and coverage XML Cobertura report for publishing task
    - name: Run pylint linter
      run: pipenv run pytest python/aswfdocker --doctest-modules --pylint --junitxml=test-pylint-results.xml --cov=. --cov-report=xml

    - name: Install and Run Sonar Scanner
      uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9 # v7.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
