name: Test Python aswfdocker Library

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      with:
        python-version: 3.9
        cache: 'pipenv'
    - name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
    - name: Install aswfdocker and dev dependencies with pipenv
      run: pipenv install --dev

    - name: Run all pre-commit tests
      run: pipenv run pre-commit run --all-files

    - name: Check that all templated Dockerfile and README.md are up to date
      run: pipenv run aswfdocker dockergen --check
