name: Test Python aswfdocker Library

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: 3.9
        cache: 'pipenv'
    - name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
    - name: Install aswfdocker and dev dependencies with pipenv
      run: pipenv install --dev

    - name: Run all pre-commit tests
      run: pipenv run pre-commit run --all-files

    - name: Check that all templated Dockerfile and README.md are up to date
      run: pipenv run aswfdocker dockergen --check
