name: Test Python aswfdocker Library

on:
  [push]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip3 install pipenv
      name: Install pipenv

    - run: pipenv install --dev
      name: Install aswfdocker and dev dependencies with pipenv

    - run: pipenv run pre-commit run --all-files
      name: Run all pre-commit tests
