name: Test Python aswfdocker Library

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.10"

    - name: Install uv
      uses: astral-sh/setup-uv@e06108dd0aef18192324c70427afc47652e63a82 # v7.5.0
      with:
        enable-cache: auto

    - name: Install aswfdocker and dev dependencies
      run: uv sync --all-extras

    - name: Run all pre-commit tests
      run: uv run pre-commit run --all-files

    - name: Check that all templated Dockerfile and README.md are up to date
      run: uv run aswfdocker dockergen --check
