name: Test Python aswfdocker Library

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - run: pip3 install pipenv
      name: Install pipenv

    - run: pipenv install --dev
      name: Install aswfdocker and dev dependencies with pipenv

    - run: pipenv run pre-commit run --all-files
      name: Run all pre-commit tests

    - run: pipenv run aswfdocker dockergen --check
      name: Check that all templated Dockerfile and README.md are up to date
