name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ${{ (github.repository_owner == 'AcademySoftwareFoundation' && 'ubuntu-22.04-8c-32g-300h') || 'ubuntu-latest' }}
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: '1'
      CONAN_LOGIN_USERNAME: ${{ secrets.ARTIFACTORY_USER }}
      CONAN_PASSWORD: ${{ secrets.ARTIFACTORY_TOKEN }}
      GITHUB_REF_LOCAL: ${{ github.ref || format('{0}{1}', 'refs/tags/', github.event.release.tag_name) }}

    strategy:
      matrix:
        group: [docker, conan]
        include:
          - group: docker
            args: ""
            build: true
            push_description: true
          - group: conan
            args: --use-conan --conan-login --build-missing
            build: ${{ contains(github.ref, '/ci-package') }}
            push_description: false

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Activate Docker buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      with:
        driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760

    - name: Set up Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      with:
        python-version: 3.9
        cache: 'pipenv'
    - name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
    - name: Install aswfdocker and dependencies with pipenv
      run: pipenv install

    - name: Login to DockerHub
      if: ${{ matrix.build }}
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u aswfdocker --password-stdin

    - name: Build and Push
      if: ${{ matrix.build }}
      run: |
        pipenv run aswfdocker \
          --repo-uri $GITHUB_REPOSITORY \
          --verbose \
          build \
          --full-name $GITHUB_REF_LOCAL \
          --push YES \
          ${{ matrix.args }}

    - name: Update Docker Hub Description
      if: ${{ matrix.push_description }}
      run: |
        pipenv run aswfdocker \
          pushoverview \
          --username aswfdocker \
          --password ${{ secrets.DOCKERHUB_PASSWORD }} \
          --full-name $GITHUB_REF_LOCAL
