name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ${{ (github.repository_owner == 'AcademySoftwareFoundation' && 'ubuntu-22.04-8c-32g-300h') || 'ubuntu-latest' }}
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: '1'
      CONAN_LOGIN_USERNAME: ${{ secrets.ARTIFACTORY_USER }}
      CONAN_PASSWORD: ${{ secrets.ARTIFACTORY_TOKEN }}
      GITHUB_REF_LOCAL: ${{ github.ref || format('{0}{1}', 'refs/tags/', github.event.release.tag_name) }}

    strategy:
      matrix:
        group: [docker, conan]
        include:
          - group: docker
            args: ""
            build: true
            push_description: true
          - group: conan
            args: ""
            build: ${{ contains(github.ref, '/ci-package') }}
            push_description: false

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Activate Docker buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      with:
        driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.9"

    - name: Install uv
      uses: astral-sh/setup-uv@e06108dd0aef18192324c70427afc47652e63a82 # v7.5.0
      with:
        enable-cache: auto

    - name: Install aswfdocker and dependencies
      run: uv sync

    - name: Login to DockerHub
      if: ${{ matrix.build }}
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u aswfdocker --password-stdin

    - name: Build and Push
      if: ${{ matrix.build }}
      run: |
        uv run aswfdocker \
          --repo-uri $GITHUB_REPOSITORY \
          --verbose \
          build \
          --full-name $GITHUB_REF_LOCAL \
          --push YES \
          ${{ matrix.args }}

    - name: Update Docker Hub Description
      if: ${{ matrix.push_description }}
      run: |
        uv run aswfdocker \
          pushoverview \
          --username aswfdocker \
          --password ${{ secrets.DOCKERHUB_PASSWORD }} \
          --full-name $GITHUB_REF_LOCAL
