name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ${{ (github.repository_owner == 'AcademySoftwareFoundation' && 'ubuntu-22.04-8c-32g-300h') || 'ubuntu-latest' }}
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: '1'
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}

    strategy:
      matrix:
        group: [docker, conan]
        include:
          - group: docker
            args: ""
            build: true
            push_description: true
          - group: conan
            args: --use-conan --conan-login --build-missing
            build: ${{ contains(github.ref, '/ci-package') }}
            push_description: false

    steps:
    - uses: actions/checkout@v4

    - name: Activate Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: 'pipenv'
    - name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
    - name: Install aswfdocker and dependencies with pipenv
      run: pipenv install

    - name: Login to DockerHub
      if: ${{ matrix.build }}
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u aswfdocker --password-stdin

    - name: Build and Push
      if: ${{ matrix.build }}
      run: |
        pipenv run aswfdocker \
          --repo-uri $GITHUB_REPOSITORY \
          --verbose \
          build \
          --full-name $GITHUB_REF \
          --push YES \
          ${{ matrix.args }}

    - name: Update Docker Hub Description
      if: ${{ matrix.push_description }}
      run: |
        pipenv run aswfdocker \
          pushoverview \
          --username aswfdocker \
          --password ${{ secrets.DOCKERHUB_PASSWORD }} \
          --full-name $GITHUB_REF
