# syntax=docker/dockerfile:1.3-labs
# Copyright (c) Contributors to the aswf-docker Project. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# !!! This file is automatically generated from a template and the `image.yaml` file in the same folder !!!

ARG ASWF_ORG
ARG ASWF_PKG_ORG
ARG CI_COMMON_VERSION
ARG ASWF_CLANG_MAJOR_VERSION
ARG ASWF_CONAN_CHANNEL


ARG ASWF_CLANG_VERSION
ARG ASWF_NINJA_VERSION
ARG ASWF_CUDA_VERSION
ARG ASWF_CCACHE_VERSION
ARG ASWF_DTS_VERSION
ARG ASWF_SONAR_VERSION
ARG ASWF_CONAN_VERSION
ARG ASWF_CONAN_PYTHON_VERSION


# Comment out this block to use Conan packages
FROM ${ASWF_PKG_ORG}/ci-package-clang:$CI_COMMON_VERSION-$ASWF_CLANG_VERSION as ci-package-clang
FROM ${ASWF_PKG_ORG}/ci-package-ninja:$CI_COMMON_VERSION-$ASWF_NINJA_VERSION as ci-package-ninja
FROM nvidia/cudagl:${ASWF_CUDA_VERSION}-devel-centos7 as ci-common


ARG ASWF_ORG
ARG ASWF_PKG_ORG
ARG ASWF_VERSION
ARG CI_COMMON_VERSION
ARG ASWF_CONAN_CHANNEL

ARG ASWF_CLANG_VERSION
ARG ASWF_NINJA_VERSION
ARG ASWF_CUDA_VERSION
ARG ASWF_CCACHE_VERSION
ARG ASWF_DTS_VERSION
ARG ASWF_SONAR_VERSION
ARG ASWF_CONAN_VERSION
ARG ASWF_CONAN_PYTHON_VERSION


LABEL org.opencontainers.image.name="$ASWF_ORG/ci-common"
LABEL org.opencontainers.image.title="Common CI Docker Image"
LABEL org.opencontainers.image.description="Contains: GCC, Clang, Jinja, ccache and all base OS libraries"
LABEL org.opencontainers.image.url="http://aswf.io/"
LABEL org.opencontainers.image.source="https://github.com/AcademySoftwareFoundation/aswf-docker/blob/master/ci-common/Dockerfile"
LABEL org.opencontainers.image.vendor="AcademySoftwareFoundation"
LABEL org.opencontainers.image.authors="Built by aswf.io CI Working Group"
LABEL org.opencontainers.image.version="${ASWF_VERSION}"



LABEL io.aswf.docker.versions.clang="$ASWF_CLANG_VERSION"
LABEL io.aswf.docker.versions.ninja="$ASWF_NINJA_VERSION"
LABEL io.aswf.docker.versions.cuda="$ASWF_CUDA_VERSION"
LABEL io.aswf.docker.versions.ccache="$ASWF_CCACHE_VERSION"
LABEL io.aswf.docker.versions.dts="$ASWF_DTS_VERSION"
LABEL io.aswf.docker.versions.sonar="$ASWF_SONAR_VERSION"
LABEL io.aswf.docker.versions.conan="$ASWF_CONAN_VERSION"


ENV ASWF_ORG=${ASWF_ORG}
ENV ASWF_VERSION=${ASWF_VERSION}


ENV ASWF_CLANG_VERSION=$ASWF_CLANG_VERSION
ENV ASWF_NINJA_VERSION=$ASWF_NINJA_VERSION
ENV ASWF_CUDA_VERSION=$ASWF_CUDA_VERSION
ENV ASWF_CCACHE_VERSION=$ASWF_CCACHE_VERSION
ENV ASWF_DTS_VERSION=$ASWF_DTS_VERSION
ENV ASWF_SONAR_VERSION=$ASWF_SONAR_VERSION
ENV ASWF_CONAN_VERSION=$ASWF_CONAN_VERSION
ENV ASWF_CONAN_PYTHON_VERSION=$ASWF_CONAN_PYTHON_VERSION


# Comment out this block to use Conan packages
COPY --from=ci-package-clang /. /usr/local/
COPY --from=ci-package-ninja /. /usr/local/
COPY ci-common/README.md ci-common/image.yaml /usr/local/aswf/

USER root

COPY scripts/common/install_yumpackages.sh \
    /tmp/

RUN /tmp/install_yumpackages.sh

RUN mkdir /opt/aswf
WORKDIR /opt/aswf

ENV LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64:/opt/rh/httpd24/root/usr/lib64:/opt/rh/devtoolset-${ASWF_DTS_VERSION}/root/usr/lib64:/opt/rh/devtoolset-${ASWF_DTS_VERSION}/root/usr/lib:${LD_LIBRARY_PATH} \
    PATH=/opt/rh/rh-git218/root/usr/bin:/usr/local/bin:/opt/rh/devtoolset-${ASWF_DTS_VERSION}/root/usr/bin:/opt/app-root/src/bin:/opt/rh/devtoolset-${ASWF_DTS_VERSION}/root/usr/bin/:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin \
    PERL5LIB=/opt/rh/rh-git218/root/usr/share/perl5/vendor_perl \
    MANPATH=/opt/rh/rh-git218/root/usr/share/man

COPY scripts/common/install_sonar.sh \
    scripts/common/install_ccache.sh \
    scripts/common/install_dev_cmake.sh \
    /tmp/

RUN export DOWNLOADS_DIR=/tmp/downloads && \
  mkdir /tmp/downloads && \
  /tmp/install_sonar.sh && \
  export PATH=${PATH}:/opt/aswfbuilder/bin && \
  /tmp/install_dev_cmake.sh && \
  /tmp/install_ccache.sh && \
  rm -rf /tmp/downloads && \
  rm -rf /opt/aswfbuilder

COPY scripts/common/setup_aswfuser.sh /tmp
RUN /tmp/setup_aswfuser.sh

ENV ASWF_CONAN_ROOT=/opt/conan

COPY ../scripts/common/install_conan.sh /tmp/

RUN --mount=type=cache,sharing=private,target=/tmp/downloads \
    /tmp/install_conan.sh

COPY ../packages/conan/settings /opt/conan_home/.conan
ENV CONAN_USER_HOME=/opt/conan_home



RUN conan config set general.default_profile=ci_common${CI_COMMON_VERSION}



# conan-only packages
COPY <<EOF /usr/local/conanfile.txt
[generators]
[imports]
., * -> .
[requires]
# Uncomment to use Conan packages instead of Docker ones
# clang/${ASWF_CLANG_VERSION}@${ASWF_PKG_ORG}/${ASWF_CONAN_CHANNEL}
# ninja/${ASWF_NINJA_VERSION}@${ASWF_PKG_ORG}/${ASWF_CONAN_CHANNEL}
EOF

RUN <<EOF
cd /usr/local/
conan install .
EOF